server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycinema
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  type-aliases-package: com.susanna.smoneybag.entity
  mapper-locations:
  - classpath*:mapper/*.xml
beetl-beetlsql: 
  dev: false
beetl: 
  suffix: html    
      